# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IN0KP9EEqPZlLRRWsCxkl7WEDWlEsSo9
"""

import pandas as pd
import matplotlib.pyplot as plt

df_tesla = pd.read_csv('tesla.csv')

print(f'Largest value for Tesla in Web Search: {df_tesla.TSLA_WEB_SEARCH.max()}')
print(f'Smallest value for Tesla in Web Search: {df_tesla.TSLA_WEB_SEARCH.min()}')
df_tesla.head()

df_bitcoin_trend = pd.read_csv('bitcoin_trend.csv')
print(f'Largest value for Tesla in Web Search: {df_bitcoin_trend.BTC_NEWS_SEARCH.max()}')